# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Instinct Wedding | Wedding Photography & Videography in Kent
email: hello@instinctwedding.com
description: 
  "Find out who is Instinct Wedding team, what we do and contact us about your wedding photography or videography."

about: 
  We are Justina and Lloyd, a wife and husband team, working together to create beautiful wedding photos and videos.
  
  <br><br>We both have background in Fine Art, and having worked and experimented with many art mediums and techniques, we fell in love with photography and video and the ability to capture memories for generations to remember.
  
  <br><br>On the wedding day, whether we are doing photography, video or both, we try and stay discreet, positive, helpful and most importantly concentrating on capturing all the beautiful moments, emotions, events as they unfold.
  
  <br><br>We live in Tunbridge Wells and are happy to cover your beautiful wedding anywhere in UK or Europe - get in touch!
  
  <br><br>When we are not working, we love spending time in nature, going on road trips and discovering heritage villages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.instinctwedding.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
